import asyncio
# import httpx  # Uncomment this when you are ready to make real HTTP calls to an AI API
# import os     # Uncomment to load your AI_API_KEY from environment variables

async def analyze_symptoms(symptoms: str) -> dict:
    """
    Analyzes a user's symptoms using an AI model.
    
    Args:
        symptoms (str): A text description of the user's symptoms.
        
    Returns:
        dict: A structured AI response containing potential conditions and advice.
    """
    # TODO: Replace the mock delay and response with a real AI API call (e.g., OpenAI, Gemini)
    # Example real implementation:
    # async with httpx.AsyncClient() as client:
    #     response = await client.post(
    #         "https://api.actual-ai-provider.com/v1/completions",
    #         headers={"Authorization": f"Bearer {os.getenv('AI_API_KEY')}"},
    #         json={"prompt": f"Analyze these symptoms: {symptoms}", ...}
    #     )
    #     return response.json()

    # Simulating network latency for the AI processing
    await asyncio.sleep(1.5)

    # Mock response structured as a real AI might return it
    return {
        "analysis_id": "mock_symp_12345",
        "provided_symptoms": symptoms,
        "preliminary_assessment": "Based on the provided symptoms, this appears to be a mild viral infection or seasonal allergies.",
        "recommendations": [
            "Rest and stay hydrated.",
            "Monitor temperature over the next 24 hours.",
            "Consult a healthcare professional if symptoms worsen or persist for more than 3 days."
        ],
        "disclaimer": "I am an AI, not a doctor. This information is for educational purposes and does not constitute medical advice."
    }


async def generate_diet_plan(age: int, height: float, weight: float, health_goal: str) -> dict:
    """
    Generates a personalized diet plan based on user metrics and goals.
    
    Args:
        age (int): User's age.
        height (float): User's height in cm.
        weight (float): User's weight in kg.
        health_goal (str): The primary goal (e.g., 'weight loss').
        
    Returns:
        dict: A structured diet plan generated by the AI.
    """
    # TODO: Replace with real AI API call
    # You would typically format the arguments into a detailed system prompt here.
    # prompt = f"Create a {health_goal} diet plan for a {age}yo, {height}cm, {weight}kg individual."

    # Simulating network latency for the AI processing
    await asyncio.sleep(2)

    # Mock response
    return {
        "plan_id": "mock_diet_98765",
        "user_profile": {
            "age": age,
            "height_cm": height,
            "weight_kg": weight,
            "goal": health_goal
        },
        "estimated_daily_calories": 2200, # This would normally be calculated by the AI
        "meal_plan": {
            "breakfast": "Oatmeal with berries and a scoop of protein powder.",
            "lunch": "Grilled chicken salad with olive oil dressing and quinoa.",
            "dinner": "Baked salmon with steamed broccoli and sweet potato.",
            "snacks": ["Greek yogurt", "Handful of almonds"]
        },
        "hydration_goal": "Drink at least 2.5 liters of water daily.",
        "disclaimer": "Please consult with a registered dietitian or doctor before making significant dietary changes."
    }